services:
  postgres:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_platform
    ports:
      - "5436:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  blog_data: